"""empty message

Revision ID: 1dfec5f4aa1f
Revises: 
Create Date: 2022-05-31 13:53:10.859144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfec5f4aa1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('answer_1', sa.Text(), nullable=False),
    sa.Column('answer_2', sa.Text(), nullable=False),
    sa.Column('answer_3', sa.Text(), nullable=False),
    sa.Column('answer_4', sa.Text(), nullable=False),
    sa.Column('right_answer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dl_id', sa.String(length=6), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('integral', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_record')
    op.drop_table('user')
    op.drop_table('question')
    # ### end Alembic commands ###
